// <auto-generated />
using System;
using EOD.DAL.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EOD.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EOD.DAL.Model.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int?>("DepartmentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("SendDate");

                    b.Property<int?>("SenderId");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SenderId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("EOD.DAL.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ManagerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EOD.DAL.Model.Document", b =>
                {
                    b.Property<string>("Path")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CaseId");

                    b.Property<string>("Status");

                    b.Property<int?>("TypeId");

                    b.HasKey("Path");

                    b.HasIndex("CaseId");

                    b.HasIndex("TypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EOD.DAL.Model.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("EOD.DAL.Model.SharedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentName");

                    b.Property<string>("RecipientMail");

                    b.Property<bool>("Seen");

                    b.Property<DateTime>("SharedTime");

                    b.HasKey("Id");

                    b.ToTable("SharedDocuments");
                });

            modelBuilder.Entity("EOD.DAL.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("Login");

                    b.Property<byte[]>("Password");

                    b.Property<string>("Role");

                    b.Property<byte[]>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "asd@asd.com",
                            FirstName = "Adam",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            Login = "superadmin",
                            Password = new byte[] { 40, 77, 29, 5, 63, 158, 90, 219, 31, 70, 65, 188, 136, 38, 148, 178, 106, 250, 201, 42, 240, 65, 64, 127, 40, 59, 168, 185, 135, 51, 160, 34 },
                            Role = "SuperAdmin",
                            Salt = new byte[] { 254, 29, 116, 157, 170, 199, 142, 247, 72, 52, 43, 159, 27, 53, 238, 157, 51, 234, 174, 18, 185, 58, 120, 171, 168, 213, 142, 125, 35, 124 }
                        });
                });

            modelBuilder.Entity("EOD.DAL.Model.Case", b =>
                {
                    b.HasOne("EOD.DAL.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("EOD.DAL.Model.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("EOD.DAL.Model.Department", b =>
                {
                    b.HasOne("EOD.DAL.Model.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("EOD.DAL.Model.Document", b =>
                {
                    b.HasOne("EOD.DAL.Model.Case", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId");

                    b.HasOne("EOD.DAL.Model.DocumentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("EOD.DAL.Model.DocumentType", b =>
                {
                    b.HasOne("EOD.DAL.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
