// <auto-generated />
using System;
using EOD.DAL.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EOD.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EOD.DAL.Model.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("SendDate");

                    b.Property<int?>("SenderId");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SenderId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("EOD.DAL.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ManagerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EOD.DAL.Model.Document", b =>
                {
                    b.Property<string>("Path")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CaseId");

                    b.Property<string>("Comment");

                    b.Property<string>("Status");

                    b.Property<int?>("TypeId");

                    b.HasKey("Path");

                    b.HasIndex("CaseId");

                    b.HasIndex("TypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EOD.DAL.Model.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("EOD.DAL.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("Login");

                    b.Property<byte[]>("Password");

                    b.Property<string>("Role");

                    b.Property<byte[]>("Salt");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "asd@asd.com",
                            FirstName = "Adam",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            Login = "superadmin",
                            Password = new byte[] { 40, 150, 3, 75, 132, 221, 40, 108, 148, 71, 119, 152, 92, 127, 35, 99, 239, 174, 78, 184, 33, 138, 32, 123, 52, 73, 198, 7, 158, 50, 130, 103 },
                            Role = "SuperAdmin",
                            Salt = new byte[] { 75, 223, 203, 56, 225, 65, 163, 5, 83, 78, 138, 38, 179, 185, 202, 191, 211, 138, 207, 72, 50, 115, 64, 101, 153, 121, 94, 112, 73, 199 }
                        });
                });

            modelBuilder.Entity("EOD.DAL.Model.Case", b =>
                {
                    b.HasOne("EOD.DAL.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("EOD.DAL.Model.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("EOD.DAL.Model.Department", b =>
                {
                    b.HasOne("EOD.DAL.Model.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("EOD.DAL.Model.Document", b =>
                {
                    b.HasOne("EOD.DAL.Model.Case", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId");

                    b.HasOne("EOD.DAL.Model.DocumentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("EOD.DAL.Model.DocumentType", b =>
                {
                    b.HasOne("EOD.DAL.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("EOD.DAL.Model.User", b =>
                {
                    b.HasOne("EOD.DAL.Model.Department")
                        .WithMany("Workers")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
